export const languageMap: Record<string, string> = {
    ru: "ru",
    en: "en",
    it: "it",
    es: "es",
    sp: "es",
    ua: "uk",
    uk: "uk",
    de: "de",
    pt: "pt",
    ro: "ro",
    pl: "pl",
    fi: "fi",
    nl: "nl",
    fr: "fr",
    bg: "bg",
    sv: "sv",
    se: "sv",
    zh: "zh",
    zh_cn: "zh",
    zh_tw: "zh_tw",
    tr: "tr",
    hr: "hr",
    ca: "ca",
};
